### ISSUE TITLE
Usability 101

### ISSUE THREAD

**Issue by ViorelMocanu** [EveryMatrix/workshops#10]
An intro into general usability principles, best practices, patterns and anti-patterns.

**Comment by CosticaPuntaru** [comment]
i think this should be an epic and have multiple issues referencing to this

**Comment by comanteodormihai** [comment]
I will prepare the presentation for this one.

**Comment by ViorelMocanu** [comment]
@comanteodormihai - please send me the presentation PDF / PPTX as soon as you can.

**Comment by ViorelMocanu** [comment]
https://www.youtube.com/watch?v=jcj4_5rst1c
https://everymatrix.com/sitebuildingacademy/EveryMatrix%20Workshops%20acadEMy%20-%20Beginners%20-%20Usability%20101.pdf
