### ISSUE TITLE
Tail call optimization

### ISSUE THREAD

**Issue by raulvasile** [EveryMatrix/workshops#33]
This is advanced, but If you start working with recursion, you must know how to optimise your code :)

**Comment by CosticaPuntaru** [comment]
some resources can be found on #25  but a full presentation is welcomed

**Comment by raulvasile** [comment]
Already got a small demo for this, based on Fibbonaci sequence :D

**Comment by CosticaPuntaru** [comment]
ill do this presentation for the next Thursday, i will aim for a 10-15 min

**Comment by raulvasile** [comment]
Ok, if you need help, let me know :)

**Comment by CosticaPuntaru** [comment]
@raulvasile  if you want it you can present it, there are many other presentations needed...

**Comment by raulvasile** [comment]
I can do it

**Comment by raulvasile** [comment]
Wrote the code for it, I hope next week I can present it :)

Link to repo: https://github.com/raulvasile/fibotail

**Comment by ViorelMocanu** [comment]
This was presented already, right?

**Comment by raulvasile** [comment]
Not by me ... don't know if @CosticaPuntaru did it

**Comment by raulvasile** [comment]
This one was presented. Link to presentation and sourcecode: https://github.com/raulvasile/fibotail

**Comment by ViorelMocanu** [comment]
Video: https://www.youtube.com/watch?v=kPBY9D5f7GM
PDF slides: https://everymatrix.com/sitebuildingacademy/EveryMatrix%20Workshops%20acadEMy%20-%20Programming%20Techniques%20-%20Tail%20Call%20Optimization.pdf
