### ISSUE TITLE
HTML 101

### ISSUE THREAD

**Issue by ViorelMocanu** [EveryMatrix/workshops#36]
How to HTML.
No, really.

**Comment by raulvasile** [comment]
HTML = how to meet ladies? If yes, then I'm in! +1

Kidding. HTML has a lot of unused tags (for example, recently I discovered that for lists `ul`, there is a special tag for list header, `lh`, which might give you a small shortcut).

**Comment by CosticaPuntaru** [comment]
well, @raulvasile you are one of the happy cases where you know a bit of html, there are others that don't know or get the meaning of some html tags... i don't want to point to specific offices, but we want to avoid having people like that between us.

**Comment by ViorelMocanu** [comment]
Video presentation: https://www.youtube.com/watch?v=XfGbd6XecNQ
PDF slides: https://everymatrix.com/sitebuildingacademy/EveryMatrix%20Workshops%20acadEMy%20-%20Beginners%20-%20Introduction%20to%20HTML.pdf
Example page (HTML): https://everymatrix.com/sitebuildingacademy/html101/example-1.rar
