### ISSUE TITLE
Why you should use TypeScript

### ISSUE THREAD

**Issue by Clokze** [EveryMatrix/workshops#46]
Small intro to typescript, why we should use typescript and how it makes our life easier, our code better and how unobtrussive it is.

**Comment by ViorelMocanu** [comment]
@arcade - you will present on the 7th of July. Is that OK for you?

**Comment by ViorelMocanu** [comment]
I haven't got either the presentation or the video recording (which I hear hasn't happened at all). Please send me at least the presentation.
