### ISSUE TITLE
Design principles

### ISSUE THREAD

**Issue by ViorelMocanu** [EveryMatrix/workshops#8]
A short intro into healthy design principles that should guide every interface design we work on.

By **design** I mean general design (ranging from industrial to fashion, from systems to the Web). With an obvious focus on web design after we take care of the generic parts. And by **web design** I mean designing interfaces (increasingly less done in PSD and more done directly in the browser).

**Comment by CosticaPuntaru** [comment]
design = psd or designing the css file structure or app structure? can you be more specific?

**Comment by CosticaPuntaru** [comment]
can we push this back one week so we will make the presentation only about js?, i think is better to target specific ppl

**Comment by ViorelMocanu** [comment]
Video: https://www.youtube.com/watch?v=mhIygKizwGg
PDF slides: https://everymatrix.com/sitebuildingacademy/EveryMatrix%20Workshops%20acadEMy%20-%20Beginners%20-%20Why%20do%20we%20need%20Design.pdf
